[package]
name = "solution_based_hint_two"
version = "0.1.0"
authors = ["'augusto.rodrigues' <guto.rodrigues1979@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
